name: Push Docker image to Docker Hub
on:
  push:
    branches:
      - master
jobs:
  push:
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: aoa7clothings
          password: dckr_pat_PBERh9BiXMJPQCpGq7SG0NGueNs
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: aoa7clothings/task1:latest